'use strict';
const KEY='ashwood-paper-lab-v1',START=400;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}};
let trades=read();
const save=()=>localStorage.setItem(KEY,JSON.stringify(trades));
function quote(){const price=Number($('price').value)/100,n=Number($('contracts').value),fee=Number($('fees').value);const cost=price*n+fee,gain=n-cost; $('cost').textContent=money(cost);$('gain').textContent=money(gain);$('breakEven').textContent=n>0?((cost/n)*100).toFixed(2)+'%':'—';return {price,n,fee,cost,gain}}
function render(){const realized=trades.filter(t=>t.status!=='OPEN').reduce((s,t)=>s+t.profit,0);const open=trades.filter(t=>t.status==='OPEN').reduce((s,t)=>s+t.cost,0);const balance=START+realized-open;let equity=START,peak=START,maxDD=0;for(const t of trades.filter(t=>t.status!=='OPEN').sort((a,b)=>a.closedAt-b.closedAt)){equity+=t.profit;peak=Math.max(peak,equity);maxDD=Math.max(maxDD,(peak-equity)/peak)}$('balance').textContent=money(balance);$('pnl').textContent=money(realized);$('closed').textContent=trades.filter(t=>t.status!=='OPEN').length;$('drawdown').textContent=(maxDD*100).toFixed(1)+'%';$('empty').hidden=trades.length>0;const root=$('ledger');root.replaceChildren();for(const t of [...trades].reverse()){const row=document.createElement('div');row.className='trade';const title=document.createElement('strong');title.textContent=t.side+' · '+t.market+' · '+t.status;row.append(title);const detail=document.createElement('p');detail.textContent=t.n+' contracts @ '+(t.price*100).toFixed(2)+'¢ · Cost '+money(t.cost)+(t.status==='OPEN'?'':' · Net '+money(t.profit));row.append(detail);if(t.reason){const note=document.createElement('p');note.textContent=t.reason;row.append(note)}if(t.status==='OPEN'){for(const [label,status] of [['Settle WIN','WIN'],['Settle LOSS','LOSS']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(!confirm('Confirm hypothetical '+status+' settlement?'))return;t.status=status;t.profit=status==='WIN'?t.n-t.cost:-t.cost;t.closedAt=Date.now();save();render()};row.append(b)}}root.append(row)}}
for(const id of ['price','contracts','fees'])$(id).addEventListener('input',quote);
$('tradeForm').addEventListener('submit',e=>{e.preventDefault();const q=quote();if(!Number.isFinite(q.cost)||q.price<=0||q.price>=1||!Number.isInteger(q.n)||q.n<1||q.fee<0||q.gain<=0)return alert('Check contract price, count and fees.');const available=START+trades.filter(t=>t.status!=='OPEN').reduce((s,t)=>s+t.profit,0)-trades.filter(t=>t.status==='OPEN').reduce((s,t)=>s+t.cost,0);if(q.cost>available)return alert('Not enough available paper balance.');trades.push({id:crypto.randomUUID(),market:$('market').value.trim(),side:$('side').value,reason:$('reason').value.trim(),...q,status:'OPEN',openedAt:Date.now()});save();render()});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,startingBalance:START,trades},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='paper-lab-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('reset').onclick=()=>{if(confirm('Delete all local paper trades? Export first if needed.')){trades=[];save();render()}};
quote();render();