import snapshot from './_design-implementation.mjs';
import { json, requireSession } from './_workspace.mjs';

// Read-only, session-protected projection for Workspace → Build → Design Implementation.
// The snapshot is generated by scripts/reconcile-design-implementation.mjs from GitHub,
// the revision each production domain actually serves, and verification records on
// ashwood-info#149. ASHWOOD displays it; it is not a place to edit status.
export default async function designHandler(req, res) {
  try {
    if (req.method !== 'GET') return json(res, 405, { ok: false, error: 'Method not allowed' });
    const session = await requireSession(req);
    if (!session) return json(res, 401, { ok: false, error: 'Workspace session required' });
    return json(res, 200, { ok: true, ...snapshot });
  } catch (error) {
    return json(res, 500, { ok: false, error: 'Design tracker unavailable' });
  }
}
